#!/bin/sh

PLAY_VERSION=play-1.2.3
PLAY_DL_LINK="http://download.playframework.org/releases/$PLAY_VERSION.zip"
PLAY_HOMES="$WORKSPACE/play-fwk"
PLAY_HOME="$PLAY_HOMES/$PLAY_VERSION"

if [ -f "$PLAY_HOME/play" ]; then
    echo "Play! Framework already installed in workspace"
	echo "Skip installation."
else
	echo "Play Framework not found in workspace"
	echo "Installation ..."

    mkdir -p "$PLAY_HOME"
    
    cd "$PLAY_HOMES"

    wget "$PLAY_DL_LINK"

    unzip "$PLAY_VERSION.zip" -x *samples-and-tests/* *documentation/* *python/* *support/*

    rm -f "$PLAY_VERSION.zip"

    echo "Installation done."
fi

echo "Use Play! Framework: $PLAY_HOME"

du -h --max-depth=0

cd "$WORKSPACE"
python "$PLAY_HOME/play" $@
rm -rf "$PLAY_HOMES"
